-- 기반 테이블: 디스코드 서버 정보
CREATE TABLE IF NOT EXISTS guilds (
    id VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    icon_url VARCHAR(255) NULL,
    owner_id VARCHAR(20) NOT NULL,
    joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
